[build.environment]
  REACT_APP_CLIENT_TYPEFORM_URL = "https://guildhq.typeform.com/to/uaDAuC"
  REACT_APP_ADVISOR_TYPEFORM_URL = "https://guildhq.typeform.com/to/aa2L2C"
  REACT_APP_RESPONSES_SPREADSHEET_ID = "1hqERQuL9Q5WGttew0v5JqxizXzBRrMoe7ID6jioT-cc"
  REACT_APP_CMS_SPREADSHEET_ID = "1So9VgfoQaC-399EW9Nic6ueI1Ta4sqdHdQ4v6ducF58"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
