[build]
  publish = "build"
  command = "yarn build"

[build.environment]
  REACT_APP_CLIENT_TYPEFORM_URL = "https://helpspace.typeform.com/to/NnvP7S"
  REACT_APP_ADVISOR_TYPEFORM_URL = "https://helpspace.typeform.com/to/SFmAoj"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"

  [headers.value]
    Access-Control-Allow-Origin = "*"
